"""add anomaly_events table

Revision ID: 3bef587b4f51
Revises: d09dfe2e0805
Create Date: 2026-08-22 23:30:08.404771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bef587b4f51'
down_revision: Union[str, Sequence[str], None] = 'd09dfe2e0805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('dataset_filename', sa.String(), nullable=True),
    sa.Column('anomaly_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('details_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_events_anomaly_type'), 'anomaly_events', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomaly_events_dataset_id'), 'anomaly_events', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_id'), 'anomaly_events', ['id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_severity'), 'anomaly_events', ['severity'], unique=False)
    op.create_index(op.f('ix_anomaly_events_status'), 'anomaly_events', ['status'], unique=False)
    op.create_index(op.f('ix_anomaly_events_timestamp'), 'anomaly_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_anomaly_events_user_id'), 'anomaly_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_username'), 'anomaly_events', ['username'], unique=False)
    op.drop_index(op.f('ix_lsh_buckets_key_type'), table_name='lsh_buckets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lsh_buckets_key_type'), 'lsh_buckets', ['bucket_key', 'band_type'], unique=False)
    op.drop_index(op.f('ix_anomaly_events_username'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_user_id'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_timestamp'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_status'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_severity'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_id'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_dataset_id'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_anomaly_type'), table_name='anomaly_events')
    op.drop_table('anomaly_events')
    # ### end Alembic commands ###
