"""add fuzzy simhash and minhash columns to datasets

Revision ID: d475e505391a
Revises: 1648add5d368
Create Date: 2026-08-22 00:05:50.539282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd475e505391a'
down_revision: Union[str, Sequence[str], None] = '1648add5d368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('simhash', sa.String(length=18), nullable=True))
    op.add_column('datasets', sa.Column('minhash_json', sa.String(), nullable=True))
    op.create_index(op.f('ix_datasets_simhash'), 'datasets', ['simhash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasets_simhash'), table_name='datasets')
    op.drop_column('datasets', 'minhash_json')
    op.drop_column('datasets', 'simhash')
    # ### end Alembic commands ###
